### ISSUE TITLE
creating a view report screen

### ISSUE THREAD

**Issue by ghost** [kivymd/KivyMD#963] opened 2021-04-16 22:54 UTC
### Description of the Bug

Hello, I have a KivyMD app and i can't figure how to create a view data screen on (View Vaccine record) that is linked to (New Vaccine). like I have the 1st screen is for data entry and I want to have another screen for viewing the data that was entered. so if y'all can check the code after clicking on login it would take you to home, after selecting from the menu click(add new vaccine) and entering the information, I want to the (View Vaccine screen) to view the records that were entered after clicking on save, here's the code for the Python scrip. it is under one whole .py file

Thaaaaanks

**Comment by podraco** [comment] 2021-04-25 03:17
## Greetings.

This channel is only for bug reports and feature requests, 

If you require assistance with KivyMD and the Kivy  framework I would recommend you to use the official discord servers.

### They can be found on the git website of each project.

In either way, you should use a recycle view or a new view (a class derived from the kivy Screen class, either by kivymd or the kivy framework). Create a load method on that screen that will receive the ID from the list screen and a screen manager to get a better support for your project.

### i'm going to close this report as it's not a bug report, nor  a feature request.

Have a great day, and I hope you have fun using KivyMD.

**Closed as completed by podraco** 2021-04-25 03:17 UTC
Labels: Resolution: Won't fix, Type: Support, Resolution: Rejected
