### ISSUE TITLE
MDDataTable isn't displaying correctly

### ISSUE THREAD

**Issue by Lightning-blade** [kivymd/KivyMD#886] opened 2021-02-22 16:57 UTC
### Description of the Bug

When there is only one row that is needed to be displayed MDDatatable does not display it correctly. I tried the same thing with multiple rows instead of just entering one row and it works correctly. It just seems to have a problem when only one row is displayed. I could be wrong about it but my code is attached here so anyone else can also verify 

### Code and Logs

```
from kivy.metrics import dp
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable

the_kv_file = '''
MDFloatLayout:
    Screen:
        id: forthetable
    
'''


class Example(MDApp):
    def __init__(self):
        super().__init__()
        self.main_screen = Builder.load_string(the_kv_file)
        self.data_tables = MDDataTable(
            size_hint=(0.9, 0.6),
            column_data=[
                ("Column 1", dp(20)),
                ("Column 2", dp(30)),
                ("Column 3", dp(50)),
                ("Column 4", dp(30)),
                ("Column 5", dp(30)),
                ("Column 6", dp(30)),
                ("Column 7", dp(30)),
            ],
            row_data=[
                # The number of elements must match the length
                # of the `column_data` list.
                (
                    "1",
                    ("alert", [255 / 256, 165 / 256, 0, 1], "No Signal"),
                    "Astrid: NE shared managed",
                    "Medium",
                    "Triaged",
                    "0:33",
                    "Chase Nguyen",
                )]
        )

    def build(self):
        self.main_screen.ids.forthetable.add_widget(self.data_tables)
        return self.main_screen


Example().run()
```

### Versions

* OS:        Windows 10
* Python:  3.8.1
* Kivy:       2.0.0rc4
* KivyMD: 0.104.2.dev0

**Comment by kevin-schumann** [comment] 2021-02-23 13:00
I am not 100% certain but I think this issue is fixed when installing the kivy master branch.

**Comment by HeaTTheatR** [comment] 2021-02-23 13:09
@kevin-schumann No, this is an obvious bug.

**Comment by kevin-schumann** [comment] 2021-02-23 13:16
![bug](https://user-images.githubusercontent.com/59102098/108848723-9e5e3e80-75e1-11eb-8916-acf2d72fba82.png)

This happens on my end with the kivy master branch installed. Where is the bug exactly? All I am saying that the issue is fixed when using the kivy master branch.

**Comment by kevin-schumann** [comment] 2021-03-14 07:09
@HeaTTheatR Did you check if this bug also occurs for you when using the kivy master branch?

**Comment by kevin-schumann** [comment] 2021-03-14 07:12
@HeaTTheatR Duplicate of #637

**Closed as completed** 2021-03-14 07:17 UTC
Labels: Type: Bug
