### ISSUE TITLE
MDSwitch Crashing

### ISSUE THREAD

**Issue by runette** [kivymd/KivyMD#863] opened 2021-02-16 15:48 UTC
### Description of the Bug

in the latest Master Branch - the MDSwitch component crashes the app. This can be reproduced using the example code for [MDSwitch from the documentation](https://kivymd.readthedocs.io/en/latest/components/selection-controls/)

### Code and Logs

Try to build this:

```python
from kivy.lang import Builder
from kivymd.app import MDApp

KV = '''
MDFloatLayout:

    MDSwitch:
        pos_hint: {'center_x': .5, 'center_y': .5}
'''

class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)

Test().run()
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

You get this:
```
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/importlib/_bootstrap.py", line 991, in _find_and_load
  return _find_and_load_unlocked(name, import_)
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/importlib/_bootstrap.py", line 975, in _find_and_load_unlocked
  module = _load_unlocked(spec)
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/importlib/_bootstrap.py", line 671, in _load_unlocked
  spec.loader.exec_module(module)
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/importlib/_bootstrap_external.py", line 783, in exec_module
  _bootstrap._call_with_frames_removed(exec, code, module.__dict__)
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/importlib/_bootstrap.py", line 219, in _call_with_frames_removed
  return f(*args, **kwds)
￼ File "/Users/paulharwood/ViRGIS-Backend/test2.py", line 18, in <module>
  Test().run()
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/site-packages/kivy/app.py", line 950, in run
  runTouchApp()
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/site-packages/kivy/base.py", line 582, in runTouchApp
  EventLoop.mainloop()
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/site-packages/kivy/base.py", line 347, in mainloop
  self.idle()
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/site-packages/kivy/base.py", line 408, in idle
  window.dispatch('on_draw')
File "/Users/paulharwood/opt/anaconda3/envs/virgis_backend/lib/python3.8/site-packages/kivy/core/window/__init__.py", line 1395, in on_draw
  self.render_context.draw()

builtins.ZeroDivisionError: float division by zero
```

### Diagnosis

I have narrowed this down to lines 220 - 245 of selectioncontrol.py - with this change you get the crash. Without it, you do not. I cannot see why this would be.

### Versions

* OS: macos
* Python: 3.8
* Kivy: 2.0.0
* KivyMD:  latest master branch as of 16/02/21

**Comment by HeaTTheatR** [comment] 2021-02-16 15:52
@runette 

https://user-images.githubusercontent.com/16930280/108087032-1085cf00-7088-11eb-81ad-82d532121783.mov

**Comment by runette** [comment] 2021-02-16 16:42
I notice that you are getting the Float Division by Zero error in the console in the background - just Pycharm looks like it is more resilient to the error than WingWare - which is crashing the app when it gets it.

I am sure you are not going to say that an uncaught `Float division by zero` is acceptable.

**Comment by HeaTTheatR** [comment] 2021-02-16 16:58
@runette Yes, I understand what the problem is ...

**Comment by HeaTTheatR** [comment] 2021-02-16 20:00
@runette This has already been fixed in my local repository. But since I still have some unfinished changes, fixes for this issue will appear a little later

**Closed as completed** 2021-02-21 15:30 UTC
Labels: Type: Bug
