### ISSUE TITLE
Can't compile KivyMd project on Appveyor - Failed to find package platform-tools

### ISSUE THREAD

**Issue by shpaginoleg7755** [kivymd/KivyMD#866] opened 2021-02-16 21:11 UTC
### Description of the Bug

Project on KivyMD (from documentation): https://github.com/WISEPLAT/test_mobile_app/blob/master/main.py
Project compile process on Appveyor: https://ci.appveyor.com/project/WISEPLAT/test-mobile-app

I have the following error:
Warning: Failed to find package platform-tools
# Command failed: /home/appveyor/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --sdk_root=/home/appveyor/.buildozer/android/platform/android-sdk platform-tools

How to fix it to get compiled apk for Android?
Please help. Thanks!!!

I used these commands to build project:
### Code and Logs

```
sudo apt -y update
sudo apt -y install libwavpack1
sudo apt -y install libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libswscale-dev libpostproc-dev
sudo apt -y install libsdl2-dev

sudo apt -y install python3
sudo apt -y install python3-pip
sudo apt -y install cython

sudo apt -y install openjdk-13-jdk
#sudo apt -y --allow-change-held-packages remove openjdk-11-jre-headless
#sudo apt purge -y openjdk-11-jre-headless
#sudo apt -y install openjdk-8-jdk #https://openjdk.java.net/install/

dpkg -l | grep openjdk

sudo apt -y install make
sudo apt -y install autoconf
sudo apt -y install libltdl-dev
sudo apt -y install libgl-dev
sudo apt -y install libssl-dev libffi-dev python3-dev
sudo apt -y install build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev
#sudo apt -y install android-sdk-platform-tools

sudo apt -y install libavcodec-dev

python3 -V
cd /home/appveyor/projects/test-mobile-app
source /home/appveyor/projects/test-mobile-app/venv/bin/activate
python3 -V

python3 -m pip install cython
python3 -m pip install kivy
python3 -m pip install kivymd
python3 -m pip install --user buildozer
#python3 -m pip install -r requirements.txt

ls -l
export PATH=~/.local/bin/:$PATH
. ~/.bashrc

ls -l
buildozer init
buildozer android debug deploy run
```

### Versions

* OS: Ubuntu 18.04
* Python: 3.6.9
* Kivy: 2.0.0
* KivyMD: latest

**Comment by podraco** [comment] 2021-02-17 05:34
I'm not sure is a KIVY related issue.

The current master branch does not correspond to the archive in pypi
You need to change the spec file buildozer creates in the folder.
Check that you main.py  file include all the libs you need, otherwise, you'll need to add them manually.

**Comment by podraco** [comment] 2021-02-17 05:48
You'll get better luck reading the buildozer docs

**Comment by podraco** [comment] 2021-02-18 06:28
As far as i know, the logs states that it was caused by buildozer/android NDK downloads process.
I'll close this issue since it's not related to kivymd directly.

As advice, you can always ask directly in the kivy discord channel
you can join with this link.
https://discord.gg/azsukt6sAA

**Closed as completed** 2021-02-18 06:28 UTC
Labels: Resolution: Won't fix, Resolution: 3rd party, Close if there is no answer
