### ISSUE TITLE
DataTable Example return an error

### ISSUE THREAD

**Issue by Lorensgt** [kivymd/KivyMD#700] opened 2020-12-01 06:51 UTC
### Description of the Bug
Greetings, I was looking at the example you have of dataTable and I have 2 errors, one is that the checkbox symbol is not displayed, nor is the sort symbol, the second error is that if I try to click on where the icon would be the application releases an error.

I hope it helps you in something. 

### Code and Logs

```from kivy.metrics import dp
from kivy.uix.anchorlayout import AnchorLayout

from kivymd.app import MDApp
from kivymd.uix.datatables import MDDataTable


class Example(MDApp):
    def build(self):
        layout = AnchorLayout()
        self.data_tables = MDDataTable(
            use_pagination=True,
            check=True,
            column_data=[
                ("No.", dp(30)),
                ("Status", dp(30)),
                ("Signal Name", dp(60), self.sort_on_signal),
                ("Severity", dp(30)),
                ("Stage", dp(30)),
                ("Schedule", dp(30), self.sort_on_schedule),
                ("Team Lead", dp(30), self.sort_on_team)
            ],
            row_data=[
                ("1", ("alert", [255 / 256, 165 / 256, 0, 1], "No Signal"),
                 "Astrid: NE shared managed", "Medium", "Triaged", "0:33",
                 "Chase Nguyen"),
                ("2", ("alert-circle", [1, 0, 0, 1], "Offline"),
                 "Cosmo: prod shared ares", "Huge", "Triaged", "0:39",
                 "Brie Furman"),
                ("3", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Phoenix: prod shared lyra-lists", "Minor",
                 "Not Triaged", "3:12", "Jeremy lake"),
                ("4", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Sirius: NW prod shared locations",
                 "Negligible",
                 "Triaged", "13:18", "Angelica Howards"),
                ("5", (
                    "checkbox-marked-circle",
                    [39 / 256, 174 / 256, 96 / 256, 1],
                    "Online"), "Sirius: prod independent account",
                 "Negligible",
                 "Triaged", "22:06", "Diane Okuma"),

            ],
            sorted_on="Schedule",
            sorted_order="ASC",
            elevation=2
        )
        self.data_tables.bind(on_row_press=self.on_row_press)
        self.data_tables.bind(on_check_press=self.on_check_press)
        layout.add_widget(self.data_tables)
        return layout

    def on_row_press(self, instance_table, instance_row):
        '''Called when a table row is clicked.'''

        print(instance_table, instance_row)

    def on_check_press(self, instance_table, current_row):
        '''Called when the check box in the table row is checked.'''

        print(instance_table, current_row)

    def sort_on_signal(self, data):
        return sorted(data, key=lambda l: l[2])

    def sort_on_schedule(self, data):
        return sorted(data, key=lambda l: sum([int(l[-2].split(":")[0])*60, int(l[-2].split(":")[1])]))

    def sort_on_team(self, data):
        return sorted(data, key=lambda l: l[-1])

Example().run()
```
```PS C:\Users\User\Desktop> python .\testkivymd.pyw                                                                                                                                                                
[INFO   ] [Logger      ] Record log in C:\Users\User\.kivy\logs\kivy_20-12-01_30.txt                                                                                                                             
[INFO   ] [deps        ] Successfully imported "kivy.deps.gstreamer"                                                                                                                                                
[INFO   ] [deps        ] Successfully imported "kivy.deps.angle"                                                                                                                                                    
[INFO   ] [deps        ] Successfully imported "kivy.deps.glew"                                                                                                                                                     
[INFO   ] [deps        ] Successfully imported "kivy.deps.sdl2"                                                                                                                                                     
[INFO   ] [Kivy        ] v1.11.1                                                                                                                                                                                    
[INFO   ] [Kivy        ] Installed at "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\__init__.py"                                                                               
[INFO   ] [Python      ] v3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]                                                                                                                 
[INFO   ] [Python      ] Interpreter at "C:\Users\User\AppData\Local\Programs\Python\Python36-32\python.exe"                                                                                                     
[INFO   ] [Factory     ] 184 symbols loaded                                                                                                                                                                         
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)                                                                                                           
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2020-12-01 (installed at "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivymd\__init__.py")                                     
[INFO   ] [Text        ] Provider: sdl2                                                                                                                                                                             
[INFO   ] [Window      ] Provider: sdl2                                                                                                                                                                             
[INFO   ] [GL          ] Using the "OpenGL" graphics system                                                                                                                                                         
[INFO   ] [GL          ] GLEW initialization succeeded                                                                                                                                                              
[INFO   ] [GL          ] Backend used <glew>                                                                                                                                                                        
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 441.41'>                                                                                                                                                    
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>                                                                                                                                                      
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1080/PCIe/SSE2'>                                                                                                                                            
[INFO   ] [GL          ] OpenGL parsed version: 4, 6                                                                                                                                                                
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>                                                                                                                                                           
[INFO   ] [GL          ] Texture max size <32768>                                                                                                                                                                   
[INFO   ] [GL          ] Texture max units <32>                                                                                                                                                                     
[INFO   ] [Window      ] auto add sdl2 input provider                                                                                                                                                               
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked                                                                                                                                      
[INFO   ] [GL          ] NPOT texture support is available                                                                                                                                                          
[INFO   ] [Base        ] Start application main loop                                                                                                                                                                
<kivymd.uix.datatables.MDDataTable object at 0x10AFD068> ['1', 'No Signal', 'Astrid: NE shared managed', 'Medium', 'Triaged', '0:33', 'Chase Nguyen']                                                               
[INFO   ] [Base        ] Leaving application in progress...                                                                                                                                                         
 Traceback (most recent call last):                                                                                                                                                                                 
   File ".\testkivymd.pyw", line 75, in <module>                                                                                                                                                                    
     Example().run()                                                                                                                                                                                                
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\app.py", line 855, in run                                                                                                
     runTouchApp()                                                                                                                                                                                                  
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\base.py", line 504, in runTouchApp                                                                                       
     EventLoop.window.mainloop()                                                                                                                                                                                    
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop                                                                       
     self._mainloop()                                                                                                                                                                                               
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop                                                                      
     EventLoop.idle()                                                                                                                                                                                               
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\base.py", line 342, in idle                                                                                              
     self.dispatch_input()                                                                                                                                                                                          
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\base.py", line 327, in dispatch_input                                                                                    
     post_dispatch_input(*pop(0))                                                                                                                                                                                   
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input                                                                               
     wid.dispatch('on_touch_up', me)                                                                                                                                                                                
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch                                                                                                                                        
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivymd\uix\behaviors\ripplebehavior.py", line 295, in on_touch_up                                                             
     return super().on_touch_up(touch)                                                                                                                                                                              
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up                                                                       
     self.dispatch('on_release')                                                                                                                                                                                    
   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch                                                                                                                                        
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch                                                                                                                                        
   File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch                                                                                                                                       
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback                                                                            
     exec(__kvlang__.co_value, idmap)                                                                                                                                                                               
   File "<string>", line 114, in <module>                                                                                                                                                                           
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivymd\uix\datatables.py", line 787, in select_all                                                                            
     cell_row_obj.ids.check.state = state                                                                                                                                                                           
   File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__                                                                                                                                      
   File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__                                                                                                                                        
   File "kivy\properties.pyx", line 544, in kivy.properties.Property.set                                                                                                                                            
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch                                                                                                                                       
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch                                                                                                                                        
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch                                                                                                                                       
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivymd\uix\selectioncontrol.py", line 372, in on_state                                                                        
     self.active = True                                                                                                                                                                                             
   File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__                                                                                                                                        
   File "kivy\properties.pyx", line 544, in kivy.properties.Property.set                                                                                                                                            
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch                                                                                                                                       
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch                                                                                                                                        
   File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch                                                                                                                                       
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback                                                                            
     exec(__kvlang__.co_value, idmap)                                                                                                                                                                               
   File "<string>", line 30, in <module>                                                                                                                                                                            
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivymd\uix\datatables.py", line 461, in select_check                                                                          
     self.table.get_select_row(self.index)                                                                                                                                                                          
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivymd\uix\datatables.py", line 674, in get_select_row                                                                        
     self._get_row_checks()  # update the dict                                                                                                                                                                      
   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivymd\uix\datatables.py", line 821, in _get_row_checks                                                                       
     if cell_row_obj.ids.check.state == "down":                                                                                                                                                                     
 AttributeError: 'NoneType' object has no attribute 'ids'   
```

### Screenshots

![Captura de pantalla 2020-12-01 074413](https://user-images.githubusercontent.com/15962677/100706287-07e6fc00-33a9-11eb-9174-1337be205a45.jpg)

### Versions

* OS: Windows 10
* Python: v3.6.1 (v3.6.1:69c0db5)
* Kivy: v1.11.1
* KivyMD: 0.104.2.dev0,

**Comment by shashi278** [comment] 2020-12-02 11:47
Hi, appreciate the detailed issue but I could not reproduce them on my end. Moreover, I think it may be because of some missing dependency that no icons are visible.

**Comment by Lorensgt** [comment] 2020-12-02 13:07
If it works when I tried to use the code using 
```pip install kivymd==0.104.1```
the icons did appear, but my intention was to test that the columns were ordered, but as I was skipping error with the lines:
```
sorted_on="Schedule",
sorted_order="ASC",
elevation=2
```
So I started to look in the bug section and noticed that it was a new feature, so I installed the development version with 
```pip install https://github.com/kivymd/KivyMD/archive/master.zip```
this is when the icons stopped appearing. Also the application directly closes, not only the error appears in the console and the application continues to work.
I guess the error lies in versions after 0.104.1 as the icons with that version if they appeared in addition to that you could select several rows without error. 
I'm sorry I can't help more because my knowledge of python is not very advanced.

**Comment by HeaTTheatR** [comment] 2021-01-10 08:21
Fixed in master branch.

**Closed as completed by HeaTTheatR** 2021-01-10 08:21 UTC
